description: >-
  A technical and cybersecurity focused blog. Covering phishing, scams, malware, and whatever else I can find.
baseurl: "/"
github_username: contrxl

permalink: /:categories/:title

header_pages:
  - index.md
  - notes.md
  - posts.md
  - about.md

footer: 'follow me on <a href="https://x.com/contrxllr">twitter</a> or get my email <a href="/about">here</a>'

plugins:
  - jekyll-seo-tag

style: dark # dark (default) or light or hacker

